# Generated by Django 3.1.6 on 2021-07-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diary'},
        ),
    ]
