# Generated by Django 3.2.5 on 2021-07-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210714_1409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diary',
            table='diary',
        ),
    ]
