# Generated by Django 3.1.6 on 2021-07-10 04:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('Equation', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
