# Generated by Django 3.1.6 on 2021-07-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210710_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equation',
            old_name='Equation',
            new_name='equation',
        ),
    ]
