# Generated by Django 3.2.5 on 2021-07-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210711_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='equation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
