# Generated by Django 3.2.5 on 2021-07-11 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210711_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='equation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
