# Generated by Django 3.2.5 on 2021-07-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_examtimetable_timetable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timetable',
            table='timetable',
        ),
    ]
