# Generated by Django 3.2.5 on 2021-07-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_timetable_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
